### PR TITLE
Merge Functional CAN TX/RX into Main

### PR DESCRIPTION
**Pull request by AdrianSucahyo**

### CODE REVIEW

**Comment by AdrianSucahyo** [comment]
CI/CD Failing because runner does not have the CAN2040 lib loaded in its installation. No issues when compiling locally.

**Review by amplifiedcactus — APPROVED** [review]
Nice work!

**Comment by chasegriswold** [comment]
Looks good to me!

**Review by chasegriswold — APPROVED** [review]
Merge it!

**Pull request merged**
